version: "2"
services:
  rabbit-mq:
    image: rabbitmq:3.4-management
    ports:
      - "8080:15672"

  starter:
    image: message-queue-client:latest
    command: ["LOAD", "A", "E", "10"]
    depends_on:
      - rabbit-mq

  a-to-b:
    image: message-queue-client:latest
    command: ["SHUFFLE", "A", "B"]
    depends_on:
      - rabbit-mq

  b-to-c:
    image: message-queue-client:latest
    command: ["SHUFFLE", "B", "C"]
    depends_on:
      - rabbit-mq

  c-to-d:
    image: message-queue-client:latest
    command: ["SHUFFLE", "C", "D"]
    depends_on:
      - rabbit-mq

  d-to-e:
    image: message-queue-client:latest
    command: ["SHUFFLE", "D", "E"]
    depends_on:
      - rabbit-mq
